### ISSUE TITLE
Wiki Setup Guide Link wrong

### ISSUE THREAD

**Issue by DWay17** [medizininformatik-initiative/feasibility-deploy#17]
In https://github.com/medizininformatik-initiative/feasibility-deploy/wiki/DSF-Middleware-Setup#step-5---share-site-information-with-central-platform the link to https://confluence.imi.med.fau.de/display/ABIDEMI/Feasibility+Setup+DSF+Client is corrupt. A search there fails ...

**Comment by DWay17** [comment]
maybe is have just no read right - I have overread it

**Comment by DiCanio** [comment]
A hint has been added to the wiki page. Thus, closing this issue.
Feel free to re-open if there is a need for.
