### ISSUE TITLE
Reverse Proxy Config

### ISSUE THREAD

**Issue by NamUKF** [medizininformatik-initiative/feasibility-deploy#22]
The feasibility triangle uses a nginx reverse proxy in its setup. 

https://github.com/medizininformatik-initiative/feasibility-deploy/blob/83ee6ef0014aacb841ccd91b9e85550efe8e0820/feasibility-triangle/rev-proxy/nginx.conf#L62

As a suggestion the header should be set to $http_host instead of host, because the blaze fhir server uses the proxy header information in order to build the self and next url, when paging. 
In order for the paging to work appropriately, given that the port is set at 444 in the feasibility deploy, the proxyheader shoudl include the port, which can be solved via this variable in the nginx.conf. 

`proxy_set_header X-Forwarded-Host  $http_host;`

**Comment by juliangruendner** [comment]
fixed in develop 

@NamUKF  - will be in next release
