### ISSUE TITLE
Add Persistent Volume to Flare Disk Cache

### ISSUE THREAD

**Issue by alexanderkiel** [medizininformatik-initiative/feasibility-deploy#42]
The Flare deployment as defined in this [Docker Compose File](https://github.com/medizininformatik-initiative/feasibility-deploy/blob/main/feasibility-triangle/flare/docker-compose.yml) misses a volume for the disk cache files. The default path is `/app/cache` as can be seen in it's [Dockerfile](https://github.com/medizininformatik-initiative/flare/blob/v1.0.0/Dockerfile). A volume is needed to separate the data of the cache DB from the rest of the container files. Especially in case the cache should be deleted, it's clear what to remove.

**Comment by juliangruendner** [comment]
FIXED in Release v3.0.0
