### ISSUE TITLE
Update Component Versions to final for Release

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-deploy#58]
Update the component versions to final for release:
https://github.com/medizininformatik-initiative/feasibility-backend/releases - v5.0.0
https://github.com/medizininformatik-initiative/feasibility-gui/releases - v2.3.4
https://github.com/medizininformatik-initiative/flare/releases/tag/v2.3.0-rc.1 v2.3.0
https://github.com/samply/blaze v0.2.8

**Comment by EmteZogaf** [comment]
done in #78
